version: '3.8'

services:
  db:
    image: postgres:15
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flora_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flora_backend
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - flora_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: flora_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - flora_network

networks:
  flora_network:
    driver: bridge

volumes:
  postgres_data: